USE MurachCollege;
GO

CREATE SCHEMA Admin;
GO

ALTER SCHEMA Admin TRANSFER dbo.Tuition;

ALTER USER JimRhodes WITH DEFAULT_SCHEMA = Admin;

GRANT SELECT, UPDATE, INSERT, DELETE, EXECUTE
ON SCHEMA :: Admin
TO JimRhodes;